# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f4d84f140e7c0ce60b4e5acd4f204a09"
name = "remix-app"
handle = "remix-app-362"
application_url = "https://boc-wrist-stops-frost.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://boc-wrist-stops-frost.trycloudflare.com/auth/callback",
  "https://boc-wrist-stops-frost.trycloudflare.com/auth/shopify/callback",
  "https://boc-wrist-stops-frost.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
