# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1f7d703e7cc37dcbb693ba2070442603"
name = "customer-loyalty-app"
handle = "customer-loyalty-app-2"
application_url = "https://rings-brazilian-arnold-proud.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_orders,write_orders,write_products,write_fulfillments,write_discounts"

[auth]
redirect_urls = [
  "https://rings-brazilian-arnold-proud.trycloudflare.com/auth/callback",
  "https://rings-brazilian-arnold-proud.trycloudflare.com/auth/shopify/callback",
  "https://rings-brazilian-arnold-proud.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
