# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f38e1d228e0e8878651b6f15a8c70bca"
name = "producct-remix-app"
handle = "producct-remix-app"
application_url = "https://enclosed-flame-queue-yemen.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://enclosed-flame-queue-yemen.trycloudflare.com/auth/callback",
  "https://enclosed-flame-queue-yemen.trycloudflare.com/auth/shopify/callback",
  "https://enclosed-flame-queue-yemen.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
